(function(){
'use strict';
const E=BossEngine,$=id=>document.getElementById(id),KEY='boss-pie-v1',SETTINGS='boss-pie-settings-v1',HISTORY='boss-pie-endings-v1';let s=null,paused=false,muted=true,audio=null,storeOK=true,history=[],last=performance.now(),saveAccum=0,endedRecorded=false;
function read(key){try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
function write(key,val){try{localStorage.setItem(key,JSON.stringify(val));return true;}catch{storeOK=false;$('save-status').textContent='瀏覽器無法儲存；這一局仍可玩，關閉後不保留。';return false;}}
function valid(v){return v&&v.version===1&&Number.isFinite(v.cash)&&v.day>=1&&v.day<=12&&Number.isFinite(v.remaining)&&v.people?.length===6&&v.people.every(p=>Number.isFinite(p.trust)&&Number.isFinite(p.fatigue))&&Array.isArray(v.logs)&&Array.isArray(v.debts)&&Array.isArray(v.events)&&v.counts&&Number.isFinite(v.progress)&&v.target===72;}
let loaded=read(KEY);if(valid(loaded))s=loaded;let prefs=read(SETTINGS);if(prefs)muted=prefs.muted!==false;history=read(HISTORY);if(!Array.isArray(history))history=[];
function save(){if(s)write(KEY,s);}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function isDialog(){return !!document.querySelector('dialog[open]');}
function blocked(){return !s||!!s.result||paused||isDialog()||!!(s.promise&&s.promise.due<=s.day);}
function open(id){if(!$(id).open)$(id).showModal();}
function close(id){$(id).close();last=performance.now();}
function feedback(message){$('feedback').textContent=message;}
function sound(){if(muted)return;try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(360,audio.currentTime);o.frequency.exponentialRampToValueAtTime(520,audio.currentTime+.1);g.gain.setValueAtTime(.022,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.16);}catch{feedback('此瀏覽器無法播放音效，遊戲仍可正常進行。');}}
Object.entries(E.ACTIONS).forEach(([id,a])=>{let b=document.createElement('button');b.id='action-'+id;b.className='action';b.innerHTML=`<span class="symbol">${a.icon}</span><b>${a.name}</b><small>${a.cost?`現金 −${a.cost} · `:''}${a.desc}</small>`;b.addEventListener('click',()=>choose(id));$('actions').append(b);});
E.create(1).people.forEach(p=>{let b=document.createElement('button');b.className='employee';b.id='employee-'+p.id;let [x,y]=BossScene.positions[p.id];b.style.left=(x-104)/11+'%';b.style.top=(y-99)/6.2+'%';b.style.width='19%';b.style.height='32%';b.addEventListener('click',()=>showPerson(p.id));$('people').append(b);});
function start(){let q=new URLSearchParams(location.search);s=E.create(q.has('qa')&&q.has('seed')?Number(q.get('seed')):undefined);paused=false;endedRecorded=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('download-status').textContent='';feedback('第一天！先看看每個決策的代價。');last=performance.now();save();render();}
function choose(id){if(!s)return;if(paused){feedback('目前暫停中；按「繼續上班」再做決策。');return;}let r=E.act(s,id);if(!r.ok){feedback(r.reason);return;}sound();feedback(`${E.ACTIONS[id]?.name||'維持現狀'}：今日產出 ${r.output.toFixed(1)}。${s.result?'本月已結算。':'新的一天開始。'}`);last=performance.now();save();render();}
function togglePause(){if(!s||s.result){feedback('請先開始一局遊戲。');return;}paused=!paused;last=performance.now();render();}
function showPerson(id){let p=s?.people[id];if(!p)return;$('person-info').innerHTML=`<p class="eyebrow">${esc(p.role)} / ${p.active?'在職':'已離職'}</p><h2>${esc(p.name)}</h2><p>${esc(p.bio)}</p><p class="person-quote">「${esc(p.quote)}」</p><div class="person-metrics"><span>信任 ${Math.round(p.trust)}</span><span>疲勞 ${Math.round(p.fatigue)}</span></div><p>${p.danger&&p.active?'⚠ 已提出警告；下次結算仍在危險狀態就會離職。':p.active?'看看他的反應，再決定下一步。':'桌上只剩下一封離職信。'}</p>`;open('person');}
function timer(){if(!s)return;$('timer').textContent=s.result?'本月結算':s.promise&&s.promise.due<=s.day?'承諾到期，等待決定':paused?'已暫停':`今日剩餘 ${Math.ceil(s.remaining)} 秒`;}
function render(){let view=s||E.create(1),m=E.metrics(view);$('day').textContent=String(view.day).padStart(2,'0')+' / 12';$('cash').textContent=Math.max(0,Math.floor(view.cash));$('progress').textContent=`${view.progress.toFixed(1)} / ${view.target}`;$('progress-bar').value=view.progress;$('trust').textContent=Math.round(m.trust);$('fatigue').textContent=Math.round(m.fatigue);$('staff').textContent=m.staff+' 人在職';$('trust-label').textContent=m.trust>=65?'願景，有人願意相信。':m.trust<35?'有人正在打開求職網站。':'嘴上說說，還是來真的？';$('equipment').textContent='設備 Lv.'+view.equipment;$('headline').textContent=view.logs.find(l=>l.weight>1)?.text||'今天的願景，可以換多少薪水？';$('sound').textContent='音效：'+(muted?'關':'開');$('pause').textContent=paused?'繼續':'暫停';$('paused-banner').hidden=!paused||!!view.result;
 $('logs').innerHTML=view.logs.slice(0,18).map(l=>`<li><time>DAY ${String(l.day).padStart(2,'0')}</time>${esc(l.text)}</li>`).join('');
 $('debts').innerHTML=view.debts.length?view.debts.map(d=>`<span class="debt ${d.status}">第 ${d.day} 天 · ${d.status==='paid'?'已付款 ✓':d.status==='broken'?'跳票！':'獎金 32 待付'}</span>`).join(''):'目前無欠條。保持下去。';
 $('event').hidden=!view.event;if(view.event)$('event').innerHTML=`<strong>${esc(view.event.name)}</strong>${esc(view.event.copy)}`;
 $('rush-status').hidden=!view.rush;if(view.rush)$('rush-status').textContent=`急單：剩 ${view.rush.remaining.toFixed(1)} 工作量 / 第 ${view.rush.due} 日截止。`;
 let due=!!(view.promise&&view.promise.due<=view.day&&!view.result);$('promise-choice').hidden=!due;$('pay').disabled=view.cash<32;$('pay-reason').textContent=view.cash<32?'現金不足 32，無法付清。':'付清後還能選擇今天的管理決策。';
 Object.keys(E.ACTIONS).forEach(id=>{let why=E.reason(view,id);$('action-'+id).setAttribute('aria-disabled',String(!!why||paused));$('action-'+id).title=paused?'目前暫停中':why||E.ACTIONS[id].desc;});$('wait').setAttribute('aria-disabled',String(!!E.reason(view,'wait')||paused));
 view.people.forEach(p=>{let b=$('employee-'+p.id);b.className='employee'+(p.active?'':' left');b.innerHTML=`<span class="${p.danger&&p.active?'danger':''}">${esc(p.name)}<i> · ${p.active?(p.danger?'想離職':p.role):'已離職'}</i></span>`;b.setAttribute('aria-label',`查看${p.name}的狀態`);});
 timer();if(view.result&&s)showEnding();
}
function showEnding(){let result=E.ENDINGS[s.result];if(!result)return;let m=E.metrics(s);$('end-title').textContent=result.title;$('end-copy').textContent=result.copy;$('end-stamp').textContent=result.stamp;$('end-stats').textContent=`第 ${s.day} 天 · 現金 ${Math.floor(s.cash)} · 進度 ${s.progress.toFixed(1)}/${s.target} · 信任 ${Math.round(m.trust)} · ${m.staff} 人在職`;$('badges').textContent=E.badges(s).length?'本月稱號：'+E.badges(s).join(' / '):'本月稱號：經營實習生';let turns=s.logs.filter(l=>l.weight>1).sort((a,b)=>b.weight-a.weight).slice(0,3).sort((a,b)=>a.day-b.day);$('turns').innerHTML=turns.map(l=>`<li>第 ${l.day} 天：${esc(l.text)}</li>`).join('')||'<li>平淡的日子，也是同事的日子。</li>';$('liabilities').textContent=[s.promise?'尚有獎金承諾 32 未兌現。':'',s.rush?`未結急單尚餘 ${s.rush.remaining.toFixed(1)} 工作量。`:''].join(' ');if(!endedRecorded){endedRecorded=true;if(!history.includes(s.result))history.push(s.result);write(HISTORY,history);save();}open('ending');}
function advance(seconds){let remaining=seconds;while(remaining>0&&s&&!s.result){if(paused||isDialog()||s.promise&&s.promise.due<=s.day)break;let dt=Math.min(remaining,s.remaining);s.remaining-=dt;remaining-=dt;if(s.remaining<=.0001){choose('wait');if(s.result)break;}}timer();}
function download(){let out=document.createElement('canvas');out.width=1080;out.height=1080;let ctx=out.getContext('2d');ctx.fillStyle='#f5f0e5';ctx.fillRect(0,0,1080,1080);ctx.fillStyle='#2f3431';ctx.font='bold 38px "Microsoft JhengHei"';ctx.fillText('老闆，餅不夠分了！',65,86);ctx.drawImage($('scene'),55,120,970,547);ctx.font='bold 48px "Microsoft JhengHei"';ctx.fillText(E.ENDINGS[s.result].title,65,755);ctx.font='26px "Microsoft JhengHei"';ctx.fillText(`現金 ${Math.floor(s.cash)} ｜ 進度 ${s.progress.toFixed(1)} ｜ 信任 ${Math.round(E.metrics(s).trust)}`,65,822);ctx.fillText(E.badges(s).join(' / ')||'每個選擇，員工都記得。',65,880);ctx.font='20px "Microsoft JhengHei"';ctx.fillText('li-syuan.github.io/boss-pie-simulator/',65,1005);out.toBlob(blob=>{if(!blob){$('download-status').textContent='圖片產生失敗，請再試一次。';return;}let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='老闆-本月戰績.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('download-status').textContent='戰績圖片已產生，請查看瀏覽器下載項目。';});}
let handlers={start:()=>{if(s&&!s.result){open('confirm');}else start();},continue:()=>{close('welcome');paused=false;endedRecorded=false;last=performance.now();render();},pause:togglePause,resume:togglePause,wait:()=>choose('wait'),sound:()=>{muted=!muted;write(SETTINGS,{muted});sound();render();},help:()=>open('rules'),'close-help':()=>close('rules'),'close-person':()=>close('person'),restart:()=>open('confirm'),'cancel-restart':()=>close('confirm'),'confirm-new':start,again:start,download,pay:()=>{if(E.settlePromise(s,true)){sound();save();render();}},'break-promise':()=>{E.settlePromise(s,false);save();render();}};Object.entries(handlers).forEach(([id,fn])=>$(id).addEventListener('click',fn));
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(['welcome','ending','confirm'].includes(d.id))e.preventDefault();last=performance.now();}));
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(s&&!s.result)paused=true;save();render();}last=performance.now();});window.addEventListener('pagehide',save);
window.bossView=()=>JSON.parse(JSON.stringify({model:s,paused,muted,history}));if(new URLSearchParams(location.search).has('qa'))window.bossQA={advance:seconds=>{advance(Math.max(0,Math.min(1000,Number(seconds)||0)));save();render();}};
function tick(now){let dt=Math.min((now-last)/1000,.25);last=now;if(!blocked()){advance(dt);saveAccum+=dt;if(saveAccum>1){save();saveAccum=0;}}BossScene.draw(s||preview,now,blocked());requestAnimationFrame(tick);}let preview=E.create(1);$('continue').hidden=!s;$('start').textContent=s?'重新開公司 →':'開公司，開演！ →';$('collection').textContent=`已收集結局 ${history.length} / 5`;render();if(s?.result)$('ending').close();open('welcome');requestAnimationFrame(tick);
})();
